<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DarkHaven.Launcher</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DarkHaven.ContentDb\DarkHaven.ContentDb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="ZstdSharp.Port" />
    <PackageReference Include="SauceControl.Blake2Fast" />
    <PackageReference Include="NSec.Cryptography" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Velopack" />
    <PackageReference Include="Microsoft.Win32.Registry" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\signing_key" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\dh-regions.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
