using System.Collections.Generic;
using System.Globalization;
using System.Numerics;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DarkHaven.Launcher.KeyGen;

/// <summary>
/// Emits <c>LaunchSigningKey.LoadShares()</c>. With no key (<c>DhLaunchKey</c> unset) it returns null and the
/// launcher signs nothing. With one, the key scalar is split into additive shares (they sum to it mod n) and each is
/// stored XOR-masked; the number of shares, the masks and the order all come from the key itself, so rotating the key
/// gives a completely different layout. The key never appears whole in the source, and neither does a fixed pattern a
/// scraper could match across releases.
/// </summary>
[Generator]
public sealed class LaunchKeyGenerator : IIncrementalGenerator
{
    private static readonly BigInteger N =
        BigInteger.Parse("0FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551", NumberStyles.HexNumber);

    // Same constant the CLI's SealScalar uses to mask the secret.
    private static readonly byte[] SecretMask = Sha256(Encoding.ASCII.GetBytes("dh-launch-mask/1"));

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var key = context.AnalyzerConfigOptionsProvider.Select((options, _) =>
            options.GlobalOptions.TryGetValue("build_property.DhLaunchKey", out var value) ? value : null);

        context.RegisterSourceOutput(key, static (spc, value) =>
            spc.AddSource("LaunchSigningKey.Shares.g.cs", SourceText.From(Emit(value), Encoding.UTF8)));
    }

    private static byte[] Sha256(byte[] data)
    {
        using var sha = System.Security.Cryptography.SHA256.Create();
        return sha.ComputeHash(data);
    }

    private static string Emit(string? sealedScalar)
    {
        var body = string.IsNullOrEmpty(sealedScalar) ? "return null;" : EmitShares(Unmask(sealedScalar!));
        return "// <auto-generated/>\n"
               + "#nullable enable\n"
               + "namespace DarkHaven.Launcher.Security;\n"
               + "public static partial class LaunchSigningKey\n{\n"
               + "    private static partial System.Collections.Generic.IReadOnlyList<byte[]>? LoadShares()\n    {\n"
               + "        " + body + "\n    }\n}\n";
    }

    private static byte[] Unmask(string sealedScalar)
    {
        var masked = System.Convert.FromBase64String(sealedScalar);
        var d = new byte[masked.Length];
        for (var i = 0; i < masked.Length; i++)
            d[i] = (byte)(masked[i] ^ SecretMask[i % SecretMask.Length]);
        return d;
    }

    private static string EmitShares(byte[] dBytes)
    {
        // A deterministic byte stream seeded from the key: same key -> same layout, a rotated key -> a new one.
        var stream = new SeedStream(dBytes);
        var d = ToScalar(dBytes);

        var shareCount = 3 + stream.NextByte() % 4; // 3..6
        var shares = new List<BigInteger>();
        var sum = BigInteger.Zero;
        for (var i = 0; i < shareCount - 1; i++)
        {
            var share = stream.NextScalar(N);
            sum = (sum + share) % N;
            shares.Add(share);
        }
        shares.Add((d % N - sum % N + N) % N);

        // Store each share XOR-masked with its own stream-derived mask; order does not matter (shares sum).
        var sb = new StringBuilder();
        sb.Append("return new byte[][] {\n");
        foreach (var share in shares)
        {
            var raw = To32(share);
            var mask = stream.NextBytes(32);
            var stored = new byte[32];
            for (var i = 0; i < 32; i++)
                stored[i] = (byte)(raw[i] ^ mask[i]);
            sb.Append("            X(new byte[]{").Append(Bytes(stored)).Append("}, new byte[]{").Append(Bytes(mask)).Append("}),\n");
        }
        sb.Append("        };\n");
        sb.Append("        static byte[] X(byte[] a, byte[] b) { var r = new byte[a.Length]; for (var i = 0; i < a.Length; i++) r[i] = (byte)(a[i] ^ b[i]); return r; }");
        return sb.ToString();
    }

    private static string Bytes(byte[] data)
    {
        var sb = new StringBuilder(data.Length * 4);
        for (var i = 0; i < data.Length; i++)
        {
            if (i != 0)
                sb.Append(',');
            sb.Append(data[i]);
        }
        return sb.ToString();
    }

    private static BigInteger ToScalar(byte[] bigEndian)
    {
        var padded = new byte[bigEndian.Length + 1]; // keep it positive
        for (var i = 0; i < bigEndian.Length; i++)
            padded[bigEndian.Length - 1 - i] = bigEndian[i];
        return new BigInteger(padded);
    }

    private static byte[] To32(BigInteger value)
    {
        var raw = value.ToByteArray(); // little-endian, possibly with sign byte
        var result = new byte[32];
        for (var i = 0; i < raw.Length && i < 32; i++)
            result[31 - i] = raw[i];
        return result;
    }

    /// <summary>SHA-256(seed ‖ counter) chained into an endless byte stream.</summary>
    private sealed class SeedStream
    {
        private readonly byte[] _seed;
        private byte[] _block = System.Array.Empty<byte>();
        private int _pos;
        private long _counter;

        public SeedStream(byte[] key)
        {
            _seed = LaunchKeyGenerator.Sha256(Concat(key, Encoding.ASCII.GetBytes("dh-launch-layout/1")));
        }

        public byte NextByte()
        {
            if (_pos >= _block.Length)
            {
                _block = LaunchKeyGenerator.Sha256(Concat(_seed, System.BitConverter.GetBytes(_counter++)));
                _pos = 0;
            }
            return _block[_pos++];
        }

        public byte[] NextBytes(int count)
        {
            var result = new byte[count];
            for (var i = 0; i < count; i++)
                result[i] = NextByte();
            return result;
        }

        public BigInteger NextScalar(BigInteger modulus)
        {
            while (true)
            {
                var padded = new byte[33];
                for (var i = 0; i < 32; i++)
                    padded[i] = NextByte();
                var value = new BigInteger(padded);
                if (value >= BigInteger.One && value < modulus)
                    return value;
            }
        }

        private static byte[] Concat(byte[] a, byte[] b)
        {
            var r = new byte[a.Length + b.Length];
            a.CopyTo(r, 0);
            b.CopyTo(r, a.Length);
            return r;
        }
    }
}
