<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DarkHaven.Cli</RootNamespace>
    <AssemblyName>dhlauncher</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DarkHaven.Launcher\DarkHaven.Launcher.csproj" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

</Project>
