<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>DarkHaven.Launcher.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DarkHaven.Launcher\DarkHaven.Launcher.csproj" />
    <ProjectReference Include="..\..\src\DarkHaven.ContentDb\DarkHaven.ContentDb.csproj" />
    <PackageReference Include="ZstdSharp.Port" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
